# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {restart}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {restart}]
set_property PACKAGE_PIN R2 [get_ports {Enable}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Enable}]

##Buttons
set_property PACKAGE_PIN U18 [get_ports snake_height_button]						
	set_property IOSTANDARD LVCMOS33 [get_ports snake_height_button]
set_property PACKAGE_PIN T18 [get_ports up_button]						
	set_property IOSTANDARD LVCMOS33 [get_ports up_button]
set_property PACKAGE_PIN W19 [get_ports left_button]						
	set_property IOSTANDARD LVCMOS33 [get_ports left_button]
set_property PACKAGE_PIN T17 [get_ports right_button]						
	set_property IOSTANDARD LVCMOS33 [get_ports right_button]
set_property PACKAGE_PIN U17 [get_ports down_button]						
	set_property IOSTANDARD LVCMOS33 [get_ports down_button]

##VGA Connector
set_property PACKAGE_PIN G19 [get_ports {red_0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red_0}]
set_property PACKAGE_PIN H19 [get_ports {red_1}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red_1}]
set_property PACKAGE_PIN J19 [get_ports {red_2}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red_2}]
set_property PACKAGE_PIN N19 [get_ports {red_3}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red_3}]
set_property PACKAGE_PIN N18 [get_ports {blue_0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue_0}]
set_property PACKAGE_PIN L18 [get_ports {blue_1}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue_1}]
set_property PACKAGE_PIN K18 [get_ports {blue_2}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue_2}]
set_property PACKAGE_PIN J18 [get_ports {blue_3}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue_3}]
set_property PACKAGE_PIN J17 [get_ports {green_0}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green_0}]
set_property PACKAGE_PIN H17 [get_ports {green_1}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green_1}]
set_property PACKAGE_PIN G17 [get_ports {green_2}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green_2}]
set_property PACKAGE_PIN D17 [get_ports {green_3}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green_3}]
set_property PACKAGE_PIN P19 [get_ports HSync]						
	set_property IOSTANDARD LVCMOS33 [get_ports HSync]
set_property PACKAGE_PIN R19 [get_ports VSync]						
	set_property IOSTANDARD LVCMOS33 [get_ports VSync]


